//HintName: AutoCompose/Sample/M08F..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 

using AutoCompose.Sample.M08A;
using AutoCompose.Sample.M08B;
using AutoCompose.Sample.M08E;

namespace AutoCompose.Sample.M08F
{
    public partial class SampleM08F
    {


        public virtual int Method3(Sample1M08A sample1, ISample2M08B sample2)
        {
            return _sample4.Method3(sample1, sample2);
        }


    }
}
