//HintName: AutoCompose/Tests/C01B..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 



namespace AutoCompose.Tests.C01B
{
    public partial class SampleC01B
    {


        public virtual int Method1()
        {
            return _sample.Method1();
        }


    }
}
