//HintName: AutoCompose/Sample/P05..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 



namespace AutoCompose.Sample.P05
{
    public partial class SampleP05
    {

        public virtual int Prop1 {  get { return _sample.Prop1; }  set { _sample.Prop1 = value; } }



    }
}
