//HintName: AutoCompose/Sample/M05..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 



namespace AutoCompose.Sample.M05
{
    public partial class SampleM05
    {


        public virtual int Method1(bool val)
        {
            return _sample.Method1(val);
        }


    }
}
