//HintName: AutoCompose/Sample/X02..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 



namespace AutoCompose.Sample.X02
{
    public partial class SampleX02
    {


        public virtual int MethodInterfaceNullable<T>(T sample) where T : ISample1X02?, ISample2X02?, new()
        {
            return _sample.MethodInterfaceNullable<T>(sample);
        }


    }
}
