//HintName: AutoCompose/Sample/C02C..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 

using AutoCompose.Sample.C02B;

namespace AutoCompose.Sample.C02C
{
    public partial class SampleC02C
    {


        public virtual int Method2()
        {
            return _sample.Method2();
        }


    }
}
