//HintName: AutoCompose/Sample/M04..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 



namespace AutoCompose.Sample.M04
{
    public partial class SampleM04
    {


        public virtual int Method1(int val1, bool val2, string val3)
        {
            return _sample.Method1(val1, val2, val3);
        }


    }
}
