//HintName: AutoCompose/Sample/M08D..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 

using AutoCompose.Sample.M08A;
using AutoCompose.Sample.M08B;
using AutoCompose.Sample.M08C;

namespace AutoCompose.Sample.M08D
{
    public partial class Sample3M08D
    {


        public virtual int Method2(ISample1M08A sample1, ISample2M08B sample2)
        {
            return _sample3.Method2(sample1, sample2);
        }


    }
}
