//HintName: AutoCompose/Sample/M03..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 



namespace AutoCompose.Sample.M03
{
    public partial class SampleM03
    {


        public virtual int Method1<TIn, TOut>(int nVal, bool bVal, string sVal, TIn sample) where TIn : new() where TOut : new()
        {
            return _sample.Method1<TIn, TOut>(nVal, bVal, sVal, sample);
        }


    }
}
