//HintName: AutoCompose/Tests/TestClasses..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 



namespace AutoCompose.Tests.TestClasses
{
    public partial class Bleck
    {

        public virtual int Prop1 {  get { return _sample.Prop1; }  set { _sample.Prop1 = value; } }



    }
}
