//HintName: AutoCompose/Sample/A02..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 



namespace AutoCompose.Sample.A02
{
    internal partial class SampleA02
    {


        public virtual int Method1()
        {
            return _sample.Method1();
        }


    }
}
