//HintName: AutoCompose/Sample/C01A..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 



namespace AutoCompose.Sample.C01A
{
    public partial class SampleC01A
    {


        public virtual int Method1()
        {
            return _sample.Method1();
        }


    }
}
