//HintName: AutoCompose/Sample/P02..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 



namespace AutoCompose.Sample.P02
{
    public partial class SampleP02
    {


    }
}
