//HintName: AutoCompose/Host/Providers..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 

using AutoCompose.Sample.X03;

namespace AutoCompose.Host.Providers
{
    public partial class AutoComposedA
    {

        public virtual int Prop1 {  get { return _baseA.Prop1; }  }


        public virtual int Prop2 {  get { return _baseA.Prop2; }  set { _baseA.Prop2 = value; } }



        public virtual void Method1()
        {
            _baseA.Method1();
        }


        public virtual void Method2()
        {
            _baseA.Method2();
        }


        public virtual int Method3(int val1, bool val2, ref string val3, out IBaseA val4)
        {
            return _baseA.Method3(val1, val2, ref val3, out val4);
        }


        public virtual void ImplementedMethod()
        {
            _baseA.ImplementedMethod();
        }


        public virtual int OverriddenMethod(int val, ref bool bVal, out string sVal)
        {
            return _baseA.OverriddenMethod(val, ref bVal, out sVal);
        }


        public virtual T GenericMethod<T>() where T : IBaseA, new()
        {
            return _baseA.GenericMethod<T>();
        }


        public virtual T GenericMethod2<T>() where T : IBaseA?, new()
        {
            return _baseA.GenericMethod2<T>();
        }


        public virtual TOut GenericMethod<TIn, TOut>(int nVal) where TIn : IBaseA, new() where TOut : IBaseA, new()
        {
            return _baseA.GenericMethod<TIn, TOut>(nVal);
        }


    }
}
