//HintName: AutoCompose/Sample/M07..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 



namespace AutoCompose.Sample.M07
{
    public partial class SampleM07
    {


        public virtual int Method1(int nVal, bool bVal, string sVal, ISampleM07 sample)
        {
            return _sample.Method1(nVal, bVal, sVal, sample);
        }


    }
}
