//HintName: AutoCompose/Sample/M06..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 



namespace AutoCompose.Sample.M06
{
    public partial class SampleM06
    {


        public virtual int Method1()
        {
            return _sample.Method1();
        }


    }
}
