//HintName: AutoCompose/Sample/P01C..g.cs
// <auto-generated> 
// WARNING: THIS CODE IS AUTO-GENERATED AT COMPILE-TIME.  ANY CHANGES WILL BE OVERWRITTEN ON NEXT COMPILE.
// </auto-generated> 

using AutoCompose.Sample.P01B;

namespace AutoCompose.Sample.P01C
{
    public partial class SampleP01C
    {


        public virtual int MethodB()
        {
            return _sample.MethodB();
        }


        public virtual int MethodB(IParameterSample parameterSample)
        {
            return _sample.MethodB(parameterSample);
        }


    }
}
